[package]
name = "golem-wasm-rpc-stubgen"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/wasm-rpc"
description = "Golem WASM RPC stub generator"

[lib]
name = "golem_wasm_rpc_stubgen"
path = "src/lib.rs"

[[bin]]
name = "wasm-rpc-stubgen"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.79"
cargo_toml = "0.19.1"
clap = { version = "4.5.0", features = ["derive"] }
cargo-component-core = "=0.7.0"
cargo-component = "=0.7.0"
dir-diff = "0.3.3"
fs_extra = "1.3.0"
golem-wasm-ast = {git = "https://github.com/golemcloud/golem-wasm-ast", branch = "fix_wasm_ast"}
golem-wasm-rpc = { path = "../wasm-rpc", version = "0.0.0" }
heck = "0.4.1"
id-arena = "2.2.1"
indexmap = "2.0.0"
pretty_env_logger = "0.5.0"
prettyplease = "0.2.16"
proc-macro2 = "1.0.78"
quote = "1.0.35"
serde = { version = "1.0.196", features = ["derive"] }
syn = "2.0.48"
tempdir = "0.3.7"
tokio = "1.36.0"
toml = "0.8.10"
wasm-compose = "0.201.0"
wit-bindgen-rust = "=0.17.0"
wit-parser = "0.201.0"
